language: cpp

sudo: false

services:
  - docker

before_install:
  - docker pull hkdaq/triggerapplication:base

install: true

script: 
  - docker run --rm -a -v `pwd`:/root/buildtest hkdaq/triggerapplication:base /bin/sh -c "cd $WCSIMDIR; source ../env-WCSim.sh; git pull; make clean; make rootcint; make; cd /root/buildtest; ln -s /TriggerApplicationPreReq/ToolDAQ/ ToolDAQ; source ./Setup.sh; make clean; make update; make"


