language: cpp

sudo: false

services:
  - docker

before_install:
  - docker pull hkdaq/triggerapplication:base

install: true

script: 
  - docker run --rm -a stdout -a stderr -v `pwd`:/root/buildtest --entrypoint /bin/sh hkdaq/triggerapplication:base -c 'cd $WCSIMDIR; source ../env-WCSim.sh; git pull; make clean; make rootcint; make; cd /root/buildtest; ln -s /TriggerApplicationPreReq/ToolDAQ/ ToolDAQ; source ./Setup.sh; make clean; make update; make'


